### PR TITLE
exclude .DS_Store (Mac OSX folder attributes)

### PR DESCRIPTION
**Pull request by hmedney**

### CODE REVIEW

**Comment by andrewferrier** [comment]
Thanks! Good addition.

**Comment by nickcmaynard** [comment]
... this should be applied to all versions of the gitignore template.

**Comment by nickcmaynard** [comment]
@hmedney Can you submit a further request with these changes applied to the other templates, please?

**Comment by andrewferrier** [comment]
Nick, already done, see my addition to the branch I merged :)

**Comment by nickcmaynard** [comment]
Ah, cool.  Apologies I missed that - it doesn't show in the merge request.

**Pull request merged**
